services:
  nginx:
    image: nginx:1.28.0-alpine3.21
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files:/app/staticfiles

  web:
    image: registry.digitalocean.com/my-registry123/mydjangoapp:1.0.0
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn mydjangoapp.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - static_files:/app/staticfiles
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  celery:
    image: registry.digitalocean.com/my-registry123/mydjangoapp:1.0.0
    restart: unless-stopped
    command: >
      sh -c "celery -A mydjangoapp worker --loglevel=info"
    env_file:
      - .env
    volumes:
      - static_files:/app/staticfiles
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  redis:
    image: redis:alpine        # Redis image
    ports:
      - "6379:6379"            # Expose Redis default port

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  static_files:
