version: '3'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile  # Specify the Dockerfile name if different
    env_file:
      - user-service.env
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - spring-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile  # Specify the Dockerfile name if different
    env_file:
      - user-service.env
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - spring-network

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  postgres_data:
