name: Deploy User Service

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-spring-user-service-with-docker.yml'
      - '.github/workflows/deploy-spring-service.yml'
      - 'myspringapp/user-service/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-spring-service.yml
    with:
      service-name: user-service
      service-dir: myspringapp/user-service
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
