name: Deploy goapp app with docker

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-goapp-with-docker.yml'
      - 'mygoapp/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Go Tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Go tests
        working-directory: ./mygoapp
        run: |
          go mod tidy
          go test ./...

  build:
    runs-on: ubuntu-latest
    name: Build app
    needs: test
    outputs:
      image_name: registry.digitalocean.com/my-registry123/mygoapp:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image
        run: |
          cd mygoapp
          docker build -t registry.digitalocean.com/my-registry123/mygoapp:${{ github.sha }} -f Dockerfile .
          docker login registry.digitalocean.com -u dockeruser -p ${{ secrets.REGISTRY_TOKEN }}
          docker push registry.digitalocean.com/my-registry123/mygoapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy app
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_REMOTE_PORT || '22' }} ${{ secrets.SSH_REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files via SCP
        run: |
          scp -P ${{ secrets.SSH_REMOTE_PORT || '22' }} -r ./mygoapp/deploy/* ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }}:/opt/mygoapp/

      - name: Restart remote app
        run: |
          ssh -p ${{ secrets.SSH_REMOTE_PORT || '22' }} ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }} << 'EOF'
            cd /opt/mygoapp/
            yq -i '.services.app.image = "${{ needs.build.outputs.image_name }}"' docker-compose.yaml
            docker compose up -d --remove-orphans
          EOF
