name: Deploy Product Service

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-spring-product-service-with-docker.yml'
      - '.github/workflows/deploy-spring-service.yml'
      - 'myspringapp/product-service/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-spring-service.yml
    with:
      service-name: product-service
      service-dir: myspringapp/product-service
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
