name: "[My django js app] Build and deploy"

on:
  push:
    branches:
      - "main"
    paths:
      - 'mydjangoapp/**'
      - '.github/workflows/mydjangoapp-build-and-deploy.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build app
    outputs:
      image_name: registry.digitalocean.com/my-registry123/mydjangoapp:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image
        run: |
          cd mydjangoapp
          docker build -t registry.digitalocean.com/my-registry123/mydjangoapp:${{ github.sha }} -f Dockerfile .
          docker login registry.digitalocean.com -u dockeruser -p ${{ secrets.REGISTRY_TOKEN }}
          docker push registry.digitalocean.com/my-registry123/mydjangoapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy app
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_REMOTE_PORT || '22' }} ${{ secrets.SSH_REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files via SCP
        run: |
          scp -P ${{ secrets.SSH_REMOTE_PORT || '22' }} -r ./mydjangoapp/deploy/* ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }}:/opt/mydjangoapp/

      - name: Restart remote app
        run: |
          ssh -p ${{ secrets.SSH_REMOTE_PORT || '22' }} ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }} << 'EOF'
            cd /opt/mydjangoapp/
            yq -i '.services.web.image = "${{ needs.build.outputs.image_name }}"' docker-compose.yaml
            yq -i '.services.celery.image = "${{ needs.build.outputs.image_name }}"' docker-compose.yaml
            docker compose up -d --remove-orphans
          EOF