name: "[My node js app] Build and deploy"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build app
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image
        run: |
          cd mynodejsapp
          docker build -t registry.digitalocean.com/my-registry123/mynodejsapp:${{ github.sha }} -f Dockerfile.production .
          docker login registry.digitalocean.com -u dockeruser -p ${{ secrets.REGISTRY_TOKEN }}
          docker push registry.digitalocean.com/my-registry123/mynodejsapp:${{ github.sha }}